### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by otgonbayar999** [NaySoftware/go-fcm#11]
Have you any example of FCM push notification?

**Comment by Depado** [comment]
There's an example in the [README.md](https://github.com/NaySoftware/go-fcm#send-to-a-list-of-devices-tokens). I don't know what else there is to say ? Could you give more context about what you're trying to achieve ?

**Comment by otgonbayar999** [comment]
Thank you for your comment, i have qt-binding golang android app which works well with mqtt eclipce broker, and following this https://firebase.google.com/docs/cloud-messaging/android/client , but i dont khow how to use   FirebaseMessagingService, FirebaseInstanceIdService java classes by go-fmc.  I need just test push nitification from FCM console to my app.

**Comment by Depado** [comment]
If you're using the FCM console, and want to act as a client I don't think that's possible using that library. This library is intented to send pushes using FCM, not to receive them (IIRC).

**Comment by otgonbayar999** [comment]
Sorry, How get registration token, i cant find in go-fcm?

**Comment by Depado** [comment]
The registration token should be available on the device.
