### ISSUE TITLE
Support for FCM Token

### ISSUE THREAD

**Issue by Depado** [NaySoftware/go-fcm#5]
Hello there 👋 

First of all thanks for the work you've put in this library 🎉 

I just noticed that on the Firebase project's setting page : 
> Firebase Cloud Messaging tokens have replaced server keys for sending messages. While you may continue to use them, support is being deprecated for server keys.

Would that be possible for you to add support for the FCM Tokens ?

Thanks a lot 🙇

**Comment by NaySoftware** [comment]
thank you @Depado , support in progress for "Firebase Cloud Messaging token"

**Comment by Depado** [comment]
Thank you for your quick reply ! 👍

**Comment by NaySoftware** [comment]
After doing some tests, the new "Firebase Cloud Messaging token" should work the exact way the "server token" worked. nothing changed.
try it! 
this issue will be closed, if something goes wrong, open a new issue with details.

**Comment by Depado** [comment]
So should I just replace the server token with the FCM token when initializing the client ?
Thanks a lot ! 🎆
